title = "gottajsx"

theme = "hugo-coder"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20
canonifyURLs = true

enableEmoji = true
enableGitInfo = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[markup.highlight]
style = "github-dark"
tabWidth = 4

[params]
author = "GottaJSX"
avatarURL = "images/avatar.jpg"
images = ["images/og_cover.png"]
description = "GottaJSX's personal site and blog"
keywords = "blog,developer,personal,software,python,c++,go,rust"
info = "Welcome, see my reminding notes"

dateFormat = "2006-01-02"

colorScheme = "dark"
hideColorSchemeToggle = true

customSCSS = ["scss/custom.scss"]

[params.goatCounter]
code = "luizdepra"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "#"

[[params.social]]
name = "Bluesky"
icon = "fa-brands fa-bluesky fa-2x"
weight = 2
url = "#"

[[params.social]]
name = "Mastodon"
icon = "fa-brands fa-mastodon fa-2x"
weight = 3
url = "#"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "#"

[[params.social]]
name = "RSS"
icon = "fa fa-rss-square fa-2x"
weight = 5
url = "/posts/index.xml"

[[menu.main]]
name = "Now"
weight = 1
url = "now/"

[[menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[menu.main]]
name = "About"
weight = 4
url = "about/"

# Configuration multilingue
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "GottaJSX"
    description = "GottaJSX's personal site and blog"
    menu = "main"

  # [languages.pt-br]
    # languageName = "Português (BR)"
    # weight = 2
    # title = "GottaJSX"
    # description = "Site pessoal e blog do GottaJSX"
    # menu = "main"
